### ISSUE TITLE
Merge with xcsoar-data-repository

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#14]
Currently we maintain xcsoar-data-repository and this one. This is especially bad because the xcsoar-data-repository maintains references to files contained in this repo.

**Comment by lordfolken** [comment]
The main reason as to why there are two: xcsoar-data-repository depends on url availability in its check. This happens before deployment of the repository file. I.e. if this data is not on the server before the xcsoar-data-repository is doing its ci-check, it will fail.

**Comment by Exadios** [comment]
So, I'm really confused now. Which two xcsoar-data-repository are you refering to?

**Comment by rawtaz** [comment]
@Exadios There's two different but related repositories:

- This one, https://github.com/XCSoar/xcsoar-data-content/, which carries a collection of data gathered mostly manually from various sources. It is used by the one mentioned below.

- And https://github.com/XCSoar/xcsoar-data-repository/, which as I understand it is used to build the a file named "repository", that XCSoar use in its "download data" feature. This repository references the one mentioned above.

**Comment by rawtaz** [comment]
@lordfolken Can you reword your last comment in more detail? I don't fully understand the dependency you are trying to explain.

**Comment by Exadios** [comment]
> @Exadios There's two different but related repositories:
> 
>     * This one, https://github.com/XCSoar/xcsoar-data-content/, which carries a collection of data gathered mostly manually from various sources. It is used by the one mentioned below.
> 
>     * And https://github.com/XCSoar/xcsoar-data-repository/, which as I understand it is used to build the [repository](http://download.xcsoar.org/repository) file of all the resources available for [xcsoar's](https://xcsoar.org) File Manager. This repository references the one mentioned above. Files here are included, and any changes to file names / paths need to be also changed / added in that repository.

So, would it be right to say that if changes are made to either this or the 'repository' those changes will make it to [repository](http://download.xcsoar.org/repository)? The reason I ask is that I want to put a small note in our culb magazine about this (or the other) repository.

**Comment by lordfolken** [comment]
I'm sorry the naming is giving people trouble. I should have thought of that.

The purpose of xcsoar-data-repository is to generate the [repository](http://download.xcosar.org/repository) file. This contains all the links to external resources (waypoints, maps, airspace, flarm, hotspots etc.) this repository file is downloaded by xcsoar when you open the file manager, and lets you choose the resources. 

Some of these links point to download.xcsoar.org. Namely the waypoints and some airspace files that have no decent place (stable, only https), to live on the internet.

They also point to the maps of download.xcsoar.org, but these are (currently, wip) unmanaged.

The main point was whether we should merge the repository (i.e. linklist) generating directory and the data directory with the waypoints/airspaces. 

In theory this sounds like a great idea. But the current continuous integration chain on the repository git project, checks all links for their availability.
I.e. if you commit a link update and a data file that wasn't available under the link, the CI chain will fail, because it would try to download the new/changed link, because the file hasn't been deployed yet.
