### ISSUE TITLE
waypoints.js only reports 0.0 for the waypoints

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#176]
@csindle hmm the waypoints.js only reports 0.0 for the waypoints:
http://download.xcsoar.org/waypoints/waypoints.js

_Originally posted by @lordfolken in https://github.com/XCSoar/xcsoar-data-content/issues/175#issuecomment-963227894_

**Comment by csindle** [comment]
Yes.



I guess that we are really looking for a country index (E.g. "Download Spain's Waypoints") and/or a map GUI to the waypoints (as opposed to the actual arithmetic average of a country's waypoints' lat and long).

I am happy to re-implement/copy the original.
Relately,


Furthermore, 


![image](https://user-images.githubusercontent.com/190719/140770648-a6cf71d6-5741-481b-88de-690a27253f5d.png)

**Comment by csindle** [comment]
https://github.com/XCSoar/mapgen/blob/e9252554909c370ca7867a74a4c947545a7609fd/bin/generate-waypoint-files#L44
