### ISSUE TITLE
Proposal: Semantic Directory Layout

### ISSUE THREAD

**Issue by csindle** [XCSoar/xcsoar-data-content#180]
#### Proposal for consolidating XCSoar data content.

This is presented as:

1. A starting point for discussing the ending point: what would be the ideal layout look like? 
1. A concrete example of the potentially useful concepts listed below in Notes.

#### Semantic Directory Layout:
Inside `data`:
```
content/
.
├── airspace
│   └── region
│       ├── Czech Wave Airspace.txt
│       ├── HWW17_Airspace_ohne.txt
│       └── Polish Wave Airspace.txt
└── waypoint
    ├── country
    │   ├── AF.cup
    │   ├── AL.cup
    │   ├── ...
    │   ├── ZM.cup
    │   └── ZW.cup
    └── region
        ├── 2019_Hotzenwald_V11.cup
        ├── CAN_PG_A-M.cup
        ├── ...
        ├── WP2020_Bronkow.cup
        └── ZA_Cape_20211007.cup


remote/
.
├── airspace
│   ├── country
│   │   ├── Australia_Airspace.txt.json
│   │   ├── Austria_Airspace.txt.json
│   │   ├── ...
│   │   ├── Ukraine_Airspace.txt.json
│   │   └── USA_Airspace.txt.json
│   └── region
│       └── Thermal_Spaces_EU.txt.json
├── flarmnet
│   └── globe
│       ├── data.fln.json
│       └── ogn-device-database.fln.json
├── waypoint
│   ├── globe
│   │   └── OpenAIP-Hotspots.cup.json
│   └── region
│       ├── TBG_DoubleSeater_tomorrow.cup.json
│       ├── TBG_SelfLaunch_tomorrow.cup.json
│       └── TBG_SingleSeater_tomorrow.cup.json
└── waypoint-detail
    └── region
        ├── TBG_AirportDetails_DoubleSeater_tomorrow.txt.json
        ├── TBG_AirportDetails_SelfLaunch_tomorrow.txt.json
        └── TBG_AirportDetails_SingleSeater_tomorrow.txt.json

source/
.
├── map
│   ├── country
│       └── ZA.xcm.json
│   └── region
│       ├── ALPS.xcm.json
│       ├── ...
│       └── US_WA_STATE.xcm.json
└── topology
```

#### Zeroth (top) Level:
1. A directory called `data`.

#### First Level:

1. Specifies what type of *data* is contained herein:  Actual content (`content`), URLs to content (`remote`), or configuration parameters on how to generate content (`source`).

1. Specifies what type of *checks* might need to be performed on the contents: E.g. `remote` URLs need to be validated  (HTTP `GET` or `HEAD`) upon PRs and regularly scheduled.

1. The directory layout on http://download.xcsoar.org/ is identical to inside `content`. Just `rsync` the whole directory across.

#### Second Level:

1. The second level directory (`map`, `waypoint`, etc.) specifies the file type.  E.g.  `type=map` in [repository](http://download.xcsoar.org/repository)

#### Third Level:

1. `*/country/*`: naming convention is ISO3166.alpha2 stem (filename sans extension), and is the [repository](http://download.xcsoar.org/repository) `area` field.

1. `region` is the old `special`.

1. `*/region/*`: The [repository](http://download.xcsoar.org/repository) `area` field will be best-effort extracted from the filename prefix (underscore separated).  E.g. `ca_quebec.*`

1. All nouns: `globe`, `region`, `country`, etc.

#### Fourth (last) Level (files):
1. One file per item. E.g. `map/country` would contain `ar.json`, `de.json`, `za.json`, etc.

1. The  [repository's](http://download.xcsoar.org/repository) `update` field is generated from the git commit date.

1. Easier to track & merge file-based edits (as opposed to a massive JSON file).

#### Misc:

1. If generated files are still required on http://download.xcsoar.org/ (*not* in any of the git repos), they should be separate from this directory layout.

1. This implies merging and removing [at least] the following git repositories:
    * https://github.com/XCSoar/xcsoar-data-repository
    * https://github.com/XCSoar/xcsoar-data-maps

---
#### "Talk is cheap. Show me the code."
https://github.com/csindle/xcsoar-data-content/tree/test/semantic_layout

---
##### source
```
$ cat data/source/map/region/ALPS.json 
{
  "bounding_box": "[4.5, 43.4, 16.5, 49.0]"
}
```

##### remote
```
$ cat data/remote/waypoint-detail/TBG_AirportDetails_DoubleSeater_tomorrow.json 
{
  "uri": "http://travelbyglider.eu/TBG_AirportDetails_DoubleSeater_tomorrow.txt"
}

$ cat data/remote/flarmnet/ogn-device-database.json 
{
  "uri": "http://ddb.glidernet.org/download/download-fln.php"
}
```
---
**All required manifest files can be automatically generated from this structure & data.**

Manifest files:

1. https://download.xcsoar.org/repository (required by XCSoar)
1. https://download.xcsoar.org/waypoints/waypoints.js **
1. https://download.xcsoar.org/waypoints/waypoints_compact.js **
1. https://download.xcsoar.org/maps/maps.config.js ** (required by `mapgen`?)
1. https://download.xcsoar.org/waypoints/xcsoar_waypoints.cup (required by `mapgen`?)
1. ~~https://download.xcsoar.org/waypoints-special/waypoints-special.json~~, ~~https://download.xcsoar.org/waypoints/waypoints-by-country.json~~,  etc.

** *Required by website.  Could they be generated as needed?*

**Comment by lordfolken** [comment]
@rawtaz can you review? i mostly agree with the layout.

**Comment by lordfolken** [comment]
We should include rasp as external source.

**Comment by lordfolken** [comment]
@csindle 
some nitpicks:
* rename globe to global
* it should be possible to have country,global,region in every folder. 
* the list country global region should not be hardcoded and be extenable with further categories which we didn't think of yet.
* the json files have to include a type. The format should be self contained and interpreted without the path location. ie. type: airspace

**Comment by csindle** [comment]
> * rename globe to global

I did initially have that, but then decided to rather be consistent and use all nouns (`globe`, `region`, `country`) or all adjectives (`global`, `regional`, `national`).  In the end I went with nouns because this repo can be viewed as one big data structure, and because the singular nouns are shorter.

---
> * the list country global region should not be hardcoded and be extenable with further categories which we didn't think of yet.

Yes, definitely: anything can be added to this directory level. The only special thing about `country` directories is that the **checks** enforce an ISO3166.alpha2 naming convention.  For `region`, a best effort guess is made for the *area* key if the filename has a country code prefix delimited by an underscore or period (makes the code elegant for handling the null case.).  E.g.  `CAN_ONT.cup` or `ZA_Cape.txt`.

---
> * it should be possible to have country,global,region in every folder.

Yes, definitely. See above. Anything can be added dynamically (no code change). 

---
> * the json files have to include a type. The format should be self contained and interpreted without the path location. ie. type: airspace

Hmmm... the whole point, and title, of this proposal is that the `airspace`, `waypoint`, `flarmnet`, `rasp`, etc. directories specify the type, so that there is no ambiguity or duplication.  I.e. The semantics of the directory layout are indeed important and do specify the file type (this is also how we know what checks [e.g. aerofiles] to run on what files.).   In my head, I model this whole repo like a nested JSON data structure, but one that it is easy to audit and collaborate on (with the power of files in git). 

---

From my side, I am now thinking that `internal` and `external` (adjectives!) might better be renamed to some nouns like `data_file` and `data_url` respectively...?

**Comment by lordfolken** [comment]
> > * rename globe to global
> 
> I did initially have that, but then decided to rather be consistent and use all nouns (`globe`, `region`, `country`) or all adjectives (`global`, `regional`, `national`).  In the end I went with nouns because this repo can be viewed as one big data structure, and because the singular nouns are shorter.
Ok i understand your reasoning there. Fine with me. 


> > * the list country global region should not be hardcoded and be extenable with further categories which we didn't think of yet.
> 
> Yes, definitely: anything can be added to this directory level. The only special thing about `country` directories is that the **checks** enforce an ISO3166.alpha2 naming convention.  For `region`, a best effort guess is made for the _area_ key if the filename has a country code prefix delimited by an underscore or period (makes the code elegant for handling the null case.). E.g. `CAN_ONT.cup` or `ZA_Cape.txt`.
> 
> > * it should be possible to have country,global,region in every folder.
> 
> Yes, definitely. See above. Anything can be added dynamically (no code change).
> 
> > * the json files have to include a type. The format should be self contained and interpreted without the path location. ie. type: airspace
> 
> Hmmm... the whole point, and title, of this proposal is that the `airspace`, `waypoint`, `flarmnet`, `rasp`, etc. directories specify the type, so that there is no ambiguity or duplication.  I.e. The semantics of the directory layout are indeed important and do specify the file type (this is also how we know what checks [e.g. aerofiles] to run on what files.). In my head, I model this whole repo like a nested JSON data structure, but one that it is easy to audit and collaborate on (with the power of files in git).
> 
> From my side, I am now thinking that `internal` and `external` (adjectives!) might better be renamed to some nouns like `data_file` and `data_url` respectively...? Also, perhaps the map creation data should rather go in `data_map`.

How about generating a 
 * internal
 * external
 * generated 
 
sort of difference? That way we have 3 basic criteria.
I would also like to generate the topology and topology layers at some point.

**Comment by csindle** [comment]
> That way we have the origin of the data clearly defined at the first level.

Yes, it makes sense to move the map parameters out of `internal`.

Yes, it makes sense for this "generated" directory to be more generic than just `map` (like you said: `topology`, `topography`, etc.).

Yes, it makes sense for the top level to specify data's origin, and delineate what steps to deploy it (beyond obviously creating the `repository` file), including the various checks.

---
Naming the top-level directories is hard, but at least easy to update in future.  I would prefer not to call the new dir `generated`, because the content still needs to *be* generated (and all of those other Manifest files are actually generated) — this dir contains the params or config to enable generation.   Perhaps:

```bash
data_content/
data_url/
data_param/
```

or:

```bash
internal/
external/
config/
```
?

**Comment by lordfolken** [comment]
data_content
data_remote
data_source 
?

i also kind of want to incoorporate https://mapgen-data.sigkill.ch/


maybe?

**Comment by csindle** [comment]
> data_content data_remote data_source ?

Yes, sounds good. I've updated the initial proposal with these suggestions.

**Comment by csindle** [comment]
> i also kind of want to incoorporate https://mapgen-data.sigkill.ch/

I'm not au fait with mapgen, so can't comment on this, but "yes" sounds great ;-)

I do however, think we should absolutely minimise the steps, and states (and therefore failure modes) between this new git repo, and Production (tighten the feedback loop), while making it super simple for developers to test their various random ideas locally.
