### ISSUE TITLE
Enhancement: Build *and* Deploy all Pull Requests to a `development` environment (if exists)

### ISSUE THREAD

**Issue by csindle** [XCSoar/xcsoar-data-content#185]
1. Currently, there is no method to test deploying one's PRs.  Only after merging into master does the PR's deploy actually get tested.  This enhancement simplifies deploying *all* PRs to the developers own testing server for verification/debugging, before creating a PR.

2. Currently, developers working on their own fork/repo on their own feature branch, never run the build checks, because the GH workflow only runs on `master` branch.  This enhancement runs the `./scripts/build.bash` on every commit to any of the developer's branches (and optionally deploys if she has set up the relevant secrets in a  GH Environment (e.g. `DEPLOY_KEY`, `DEPLOY_HOST`, etc.).

To do this:

1. ~Set up a `development` [GH Environment](https://github.com/XCSoar/xcsoar-data-content/settings/environments) for this repository, and with the relevant secrets (maybe copy all and only update `DEPLOY_PATH` to a new value?)~
2. Move the existing [secrets](https://github.com/XCSoar/xcsoar-data-content/settings/secrets/actions) to a `production` GH Environment.
3. Merge: https://github.com/XCSoar/xcsoar-data-content/pull/184

**Comment by lordfolken** [comment]
There is considerable danger with allowing some third party to deploy something publicly. 

My proposal would be:

* deploy to a local directory
* spawn a webserver in the gh environment
* check against that webserver

We are really testing the PR contents here, not the deployment process.

**Comment by csindle** [comment]
> There is considerable danger with allowing some third party to deploy something publicly.
Yes, I agree. 

Perhaps the responsibility for checking the "deployability" (e.g. deployment related edits) of PRs does not lie with this repo.  I.e.: if the dev specifically wishes to test deployment edits, she must do it on her own server (within her own `development` GH Environment).
