### ISSUE TITLE
Test files for validity on CI server

### ISSUE THREAD

**Issue by Turbo87** [XCSoar/xcsoar-data-content#2]
We should configure TravisCI to run some code that validates the files. Using https://github.com/Turbo87/aerofiles/ might be an option.

**Comment by lordfolken** [comment]
This is now implemented for waypoint files. 
Needs to be still implemented for:

- [ ] Airspaces

**Comment by lordfolken** [comment]
https://github.com/XCSoar/xcsoar-data-content/blob/master/check.sh implements 
https://github.com/XCSoar/xcsoar-data-content/blob/codacywarnings/script/check/check_airspaces.py
