### ISSUE TITLE
Create MW data

### ISSUE THREAD

**Issue by espwx** [XCSoar/xcsoar-data-content#200]
1. Add current MW Waypoints to include ALL airfields, with better descriptions
2. Create an Airspace file for MW
3. Create a terrain file for MW

I have access to all this information, but need to better understand the required format to enable me to create a pull request - will do some reading to aquire this information.

**Comment by lordfolken** [comment]
The main format for waypoints is cup and openair for airspace. 
http://download.naviter.com/docs/CUP-file-format-description.pdf
http://winpilot.com/usersguide/userairspace.asp

Please have a look at those and at the content here.

**Comment by espwx** [comment]
Thanks for the useful links - have started browsing the information!

**Comment by lordfolken** [comment]
Sorry could you en light me on MW ? Where is it?
Terrain files you can try to generate with http://mapgen.xcsoar.org/

Also i'd be interested in what barriers of entry you encounter.

**Comment by espwx** [comment]
Malawi is a small(ish) country in Central Africa. We have about 20 something aircraft on the national register and there is a rather limited amount of aviation activity, which has been declining over the years. My hope is that by making the aviation data more available it may contribute in a small way to get general aviation on an uphill trajectory again.

I did get the terrain data for malawi generated and it works fine.

I have reviewed the available airspace and waypoint data. 

1) The main issue is to actually plot this in QGIS and correct for some of the inaccuracies of intersecting airspace points to end up with closed shapes. QGIS seems like the right program for such a task, yet it is seemingly cumbersome to plot simple geometric shapes like circles or straight lines with snapping support.

2) Another issue is the datum of the published data - some is in WGS84 while older data is in some obscure "Modified Clake 1880" format? If anyone can point to the correct datum in QGIS, that would be very helpful. Maybe we need to manually correct the waypoints by comparing with known features?

The waypoint data has mostly been digitized into CSV files for import into QGIS. Just as soon as the datum issue is resolved this should be straight forward.

**Comment by espwx** [comment]
Here is a first working version of the 3 files. Feedback is welcome for anyone trying them. You will need to rename the cup.txt file to just .cup and unip the xcm.zip file. Then copy all into the XCsoar data directory and select the files under "config", "system", "files".

[Malawi.txt](https://github.com/XCSoar/xcsoar-data-content/files/7794168/Malawi.txt)
[Waypoints.cup.txt](https://github.com/XCSoar/xcsoar-data-content/files/7794169/Waypoints.cup.txt)
[Malawi.xcm.zip](https://github.com/XCSoar/xcsoar-data-content/files/7794183/Malawi.xcm.zip)
.

**Comment by lordfolken** [comment]
Very good.

Airspace: add the file here as Malawi_Airspace.text https://github.com/XCSoar/xcsoar-data-content/tree/master/data/content/airspace/country/

Waypoints merge yours and what is in:
https://github.com/XCSoar/xcsoar-data-content/blob/master/data/content/waypoint/country/MW.cup

Please check the current contents and replace and verify what you can.

Map: the map is generated from the coordinate set:
Example: 
https://github.com/XCSoar/xcsoar-data-content/blob/master/data/source/map/region/UA.json

Create a MW.json just like it.

**Comment by lordfolken** [comment]
Once we merge your pull request all the files will be available from the file manager in xcsoar. Config->Config->file manager

**Comment by espwx** [comment]
done
https://github.com/XCSoar/xcsoar-data-content/pull/203

**Comment by lordfolken** [comment]
Congrats. :) 
I need to generate the map.

**Comment by espwx** [comment]
Nice. I see that the MW waypoints and Airspace are now available for download. However, the terrain file is displayed, but not downloadable. Is this because you still need to "generate the map"? Or is there another problem with the json file?
