### ISSUE TITLE
Turkey Map add ? 

### ISSUE THREAD

**Issue by sukrun** [XCSoar/xcsoar-data-content#222]
Hi everyone, i can't find any map for using in Turkey, it should be good if there is no map the app use google's map  ?

**Comment by lordfolken** [comment]
Hello, 

Please create a PR for Turkey and add it to https://github.com/XCSoar/xcsoar-data-content/tree/master/data/source/map/
Then the map will be generated and added to the repository/download/inapp FIle Manager.

**Comment by sukrun** [comment]
I don't know how can I create PR, can you please tell me how can I do that ? 
I ve try to create a map file from here http://mapgen.xcsoar.org/  
but I can't download the file created

**Comment by lordfolken** [comment]
I think the best howto is here:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

What is needed is a file in json format in the directory here:
https://github.com/XCSoar/xcsoar-data-content/tree/master/data/source/map/region

The contents are relatively simple, here the ALPS region as an example:
https://github.com/XCSoar/xcsoar-data-content/blob/7630d34975efa0f35a7ad0d81f47b3524f7889e9/data/source/map/region/ALPS.json#L1

These are the coordinates, that you can get from the [mapgen](http://mapgen.xcsoar.org) webinterface interface.

**Comment by lordfolken** [comment]
So the whole of turkey should be something like: 
```json
{"bounding_box": [25.1, 35.9, 45.1, 42] }
```
That would be the largest map however. Maybe multiple regions would make sense.
