### ISSUE TITLE
Status badge does not update

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#235]
The [repository check workflow](https://github.com/XCSoar/xcsoar-data-content/tree/master/.github/workflows/check_repo_urls.yml)'s Badge is shown as failing, despite the recent workflow runs succeeding.

**Comment by rawtaz** [comment]
Looking at the history in https://github.com/XCSoar/xcsoar-data-content/actions/workflows/check_repo_urls.yml it doesn't seem to be running at all?

**Comment by rawtaz** [comment]
Could it be one level of indentation missing on lines 5-7 ?

**Comment by lordfolken** [comment]
The last run lists:
19 hours ago 1m 52s 
It runs on shedule:
https://github.com/XCSoar/xcsoar-data-content/blob/9af3967cad09479cf3a8779305f4121a5c23a7dd/.github/workflows/check_repo_urls.yml#L3-L7

**Comment by rawtaz** [comment]
Right, sorry. That makes sense.

**Comment by rawtaz** [comment]
I deleted the two red/failed workflow runs from the history (they were from just four days back in time), this made the badge go green again. Let's hope it stays that way.
