### ISSUE TITLE
UK_Airspace.txt outdated

### ISSUE THREAD

**Issue by SoaringMLJ** [XCSoar/xcsoar-data-content#280]
This file is outdated (Feb 2020) and is missing key airspace.
Please can it be deleted in the absence of a maintainer?

Background:
This file has been generated from https://asselect.uk/ which allows users to create an up-to-date file and which is updated every four weeks. If the file is going to exist at all in xcsoar-data-content, it would need to have a maintainer that is prepared to update it on this frequency.

Many users in any case will prefer to use https://asselect.uk to create their own file with their choices of what to include in the file.

**Comment by lordfolken** [comment]
I still don't understand this uk-only method of prefiltering airspaces.

@ahsparrow
It looks like a web frontend (previously was a windows exe), so it could easily generate a file on a static url which we could include as a remote source with the most common values preselected. This could then easily be included via the file manager. That way it would remain current and there we'd offer something to the user.

Copying files into XCSoar (on android) is increasingly made difficult as the google eco system undermines system functionality. So not being able to download from inside xcsoar is. 

Example how we handle the other cases:
https://github.com/XCSoar/xcsoar-data-content/tree/master/data/remote/airspace/country

**Comment by SoaringMLJ** [comment]
I think that there are a number of separate tasks here:

1) Most urgent: remove the out of date file. Better that a user has to ask about how to obtain an up-to-date file than simply use an out-of-date one. Example: the airspace directly above our club has recently changed and airliners are routed through it to major London airports.

2) I like your idea of using ASSelect to generate a file at a static location if that can be made to work.

3) Following 2, provide the user with a way an easy way to determine how old their file is, and update it if required. As I understand it, the file must be downloaded by the user - it is not pushed. I suggest that the embedded date is left in the airspace filename so that the user can see easily the date of their file, and, when they press 'download' they can see if there is a more up-to-date version, and download it if necessary. This does of course mean that the filename on the server will change every 4 weeks.

(It is really unhelpful that the original uk2020-02-27.txt file was renamed UK_Airspace.txt as this gives the user no clue that the file that they are using is so out-of-date.)

**Comment by ahsparrow** [comment]
Sorry, but you won't be able to use ASSelect directly - the data is 
generated in the browser using JavaScript
Alan

**Comment by lordfolken** [comment]
The file manager in xcsoar is capable of comparing files to local files. However for that the url must change then then update= tag in the repository files https://download.xcsoar.org/repository is set, signaling an update to the user, as the repository file is downloaded on startup.

How up2date is openaip's data for the UK?

**Comment by SoaringMLJ** [comment]
I'm not quite clear on the details of the update process. Does the user receive a prompt, or is the update done silently? Does this rely on an internet connection being available on startup? Does XCSoar know if the file has been loaded manually into the device's directory or been downloaded from within the application?

OpenAIP doesn't look too bad, but I really can't speak about its overall accuracy. The very latest changes from ASSelect are not there, but it looks to have had edits from July 2022. Some of the data are clearly from an ASSelect-derived file. For gliding, it would be much better to use the ASSelect file directly.

I have generated an ASSelect file from the website with a sensible set of default options, excluding local agreements and RA(T)s, but including radio frequencies and wave boxes. The full set of selections is in the file:
airspace:{atz:ctr,ils:classg,unlicensedAirfield:classg,
* glidingAirfield:classf,homeAirfield:None,
* microlightAirfield:classg,hirtaGvs:exclude,obstacle:exclude},
* options:{maxLevel:66000,radioFreqs:append,north:59,south:49,
* format:openair},rats:[],loas:[],waves:[NSGA BORDERS,NSGA DARTMOOR,
* NSGA DERBYSHIRE,NSGA SCOTLAND,NSGA WALES,NSGA YORKSHIRE,
* TRAG ABOYNE,TRAG NORTHUMBRIA,TRAG PORTMOAK,TRAG SCOTLAND LOWER,
* TRAG SCOTLAND UPPER,TRAG SPADEADAM LOWER,TRAG SPADEADAM UPPER,
* TRAG WALES LOWER,TRAG WALES UPPER,TRAG YORKSHIRE LOWER,
* TRAG YORKSHIRE UPPER]

(Class F isn't currently used in the UK, so classifying gliding sites as class F in the file is a handy way of representing them differently on the map.)

[uk2022-08-11.txt](https://github.com/XCSoar/xcsoar-data-content/files/9377178/uk2022-08-11.txt)

Of course this is a manual process which isn't ideal for the future.

**Comment by lordfolken** [comment]
If you solely rely on XCSoar for your gliding decisions, you will die. 

XCSoar isn't a certified flight instrument. Its purely informal and can only serve as secondary information. No guarantee or fit for purpose of any kind.

 It doesn't replace your paper maps. Nor your role as PIC.

The update process for the file is to open the file manager. It will show which resources are out of date, if your device has internet. You then need to select update all and wait for the downloads. A popup would be nice, but it isn't currently implemented.

Currently the update is only signaled, if the file on this repo changes. For remote files one can add a random text string to the json.

Potenially the process of how you generated the file could be automated with selenium?

**Comment by SoaringMLJ** [comment]
This is understood, and personally I would never blindly download an airspace file unless I was reasonably confident of where it has come from. Nevertheless, an out-of-date file is trap particularly for the inexperienced, who may make assumptions.

I don't know Selenium but automation sounds interesting.

**Comment by lordfolken** [comment]
Why dont we readd the file with a current version? Everyone that has it will get an update. Because now they will never know that they have an out of date file.

**Comment by SoaringMLJ** [comment]
Thanks for uploading the latest airspace.

I think that we now have a choice:

1) Have a system for keeping it up-to-date.
2) Delete the file at the end of the season. Since this will not show to users that they have an out-of-date file, perhaps we could push an update with an empty file so that users are forced to find an up-to-date file.

**Comment by lordfolken** [comment]
There is a system in place to keep the airspace files up to date. Today. 
I think you should lobby for an official airspace file for your country.

**Comment by SoaringMLJ** [comment]
@ahsparrow has kindly provided a file on a static url that will be updated on the 4 week AIRAC cycle. 
https://asselect.uk/default/openair.txt
Are you able to work some magic with this, please?
