### ISSUE TITLE
Error in canada namespace

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#290]
@ventus99 
![Screenshot_20220913-135521](https://user-images.githubusercontent.com/407371/189895057-90f6bbe1-a64e-4d2c-bbcb-1bded54af398.png)

**Comment by ventus99** [comment]
Thanks for pointing that out.  I usually test it on my windows version of XCSoar.  That version did not have any problem.  Only on Android.  I have fixed it and created a pull request.  It is tested on Android.

**Comment by lordfolken** [comment]
Thanks for the fix. Be sure to download the latest windows version: https://downloads.xcsoar.org/releases/
The airspace parser has become more strict with at about v7.24. Previously air spaces where just silently dropped.
