### ISSUE TITLE
problems loading germany.cup via Dateimanger in XCSOAR Android

### ISSUE THREAD

**Issue by saschadaehne** [XCSoar/xcsoar-data-content#3]
When loading the Germany.cup file via xcsoar 6.8.10Android, a html file of the github page with the name Germany.cup is loaded.
Of course this html file can not be interpreted by XCSOAR and the waypoints corrupted. May be the problem is more on XCSOAR site.
Other waypoint files, like Poland.cup are downloaded correctly.

**Comment by Turbo87** [comment]
this was fixed by https://github.com/XCSoar/xcsoar-data-repository/pull/95 :)
