### ISSUE TITLE
Fuentemilanos

### ISSUE THREAD

**Issue by Jean-Yves-Fayence** [XCSoar/xcsoar-data-content#397]
L'info de l'orientation de la piste est fausse. C'est une 16/34 et non une 05!

Welcome! - We kindly ask that you:

  1. Fill out the issue template below - not doing so needs a good reason.
  2. Use the forum if you have a question rather than a bug or feature request.

The forum is at: https://forum.xcsoar.org

Thanks for understanding, and for contributing to the project!

-->

XCSoar versions having the problem
-------------------------------------------------

XCSoar versions not having the problem
-------------------------------------------------

System information
------------------

Steps to reproduce the behavior
-------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by lordfolken** [comment]
Il est corrigé dans l'ancien format de fichier. Merci de vérifier les autres aérodromes que vous connaissez.

**Comment by lordfolken** [comment]
Also 72cd937c31bc82b18915674aa8ee813df0fd8075 updates spanish airspace.
