### ISSUE TITLE
Content differences between this repo and http://download.xcsoar.org/

### ISSUE THREAD

**Issue by RBE-Avionik** [XCSoar/xcsoar-data-content#6]
I few days ago i updated the radio frequencies in "Germany.cup", than after updating the waypoints on my phone via XCSoar-Filemanager i wondered why i still had the old frequencies.

It seems that the content on "http://download.xcsoar.org/" was last time updated on "03-Jul-2018". Is there a procedure to sync this server with this repo? It would be really nice to do this....

**Comment by Turbo87** [comment]
I think @lordfolken was the last one to touch this. any idea?

**Comment by lordfolken** [comment]
For some reason CI/CD wasn't triggered upon push, even though all settings where correct.
