### ISSUE TITLE
BUG: Download link for waypoint file is broken for the countries that have a space in the name.

### ISSUE THREAD

**Issue by brunotag** [XCSoar/xcsoar-data-content#70]
Download of waypoints is broken for all the countries having a space in the name.

commit 9f2eba708dc0f309232719e30820030328e47b9a broke the waypoint download links for a bunch of countries.

https://www.xcsoar.org/download/waypoints/

Try for instance New Zealand

#69 (wow I got my favourite number PR) should fix the issue, as a quick fix. A proper fix is suggested in the PR.

**Comment by lordfolken** [comment]
Looks like I forgot the website download map. Good catch!
We need to add this to the CI checks.
