### ISSUE TITLE
Suitable airfield=?

### ISSUE THREAD

**Issue by mlep** [XCSoar/xcsoar-data-content#85]
While cleaning the file France.cup, I came to wonder if we want in the cup files all the existing airfields.

My rationale is that we want only waypoints with the label airfields (i.e. 2, 4 or 5; see below) if they are a suitable for landing a sailplane or for orientation purpose (like major airports).

Here is a proposal for the kind of airfields we do NOT want in the cup files:
- altisurfaces. But could be labelled as waypoint (label 1) or outlanding (label 3) depending on the condition (some are on glaciers...).
- very small airfields, essentially too narrow and too short for sailplanes (like the ones dedicated to ultralight trikes). Which criterias (length and width) to sort them out, and to label it as an airfield (2), an outlanding (3), a waypoint (1) or to discard it?
- helistation. To be set as a waypoint (label 1)?
- any other type of airfield to discard?
Thank you for your input.

**Comment by lordfolken** [comment]
I see what you want to do but please consider:
* soaring users of xcsoar are actually a minority (PG outnumber us by far) therefore its wrong to assume what aspects of selection are actually relevant for the particular user.
* xcsoar should always offer the information unfiltered, the pilot has to make the choices. 
* ultimately filtering data would also shift responsibility to us and possibly lure the user into a false sense of security. 
* There might be other aspects than runway/length/size/surface that prevent a glider landing at a particular sport (example: power lines on final..)

If you want to implement something like this, then that should be part of the aircraft type selection inside XCSoar.

**Comment by mlep** [comment]
Thanks for your reply. Indeed, I have a biased view of XCSoar!
So, I will go for an input of all airfields, and let pilots decide.
