### ISSUE TITLE
Airfield type

### ISSUE THREAD

**Issue by mlep** [XCSoar/xcsoar-data-content#86]
As stated in issue  #83: 

> The waypoint type (Field 7) shows that its an airport: there are 3 values in existence:
> 2 Airfield with grass surface runway
> 4 Gliding airfield
> 5 Airfield with solid surface runway

I would like to have some clarifications about the type of airports to specify in the cup file depending on the airfield condition:

* Some airfields have both a solid and a grass surface. I suggest to use label 2 if there is a grass surface runway, and label 5 if there is *only* a solid surface runway. My rationale is as follow:
  - if you have the label "grass runway", you will see in any case the solid runway nearby.
  - we prefer to land on a grass runway, so indicate that there is one.

* About label 4 (Gliding airfield), what is your understanding: an "airfield dedicated to gliding only" (i.e. "vélisurface" in French) or an airfield with a gliding activity?

Please, comment.

**Comment by lordfolken** [comment]
Please use your ICAO Chart as basis for this information. The map should represent a similar and especially familiar view to the pilot. Additional logic will complicate things. 

The french icao chart uses a glider symbol (GLD Activity in the Legend) to signify a field with gliding activity (doesn't have to be exclusive) (type 4)

If there is a solid runway it should be indicated as such, regardless of the presence of a grass runway. 

France ICAO Map:
https://www.geoportail.gouv.fr/carte

France ICAO Chart legends:
https://www.geoportail.gouv.fr/depot/layers/GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-OACI/legendes/GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-OACI-legend.pdf

Again: Using XCSoar should not replace proper flight preparation.

**Comment by lordfolken** [comment]
The presence of a grass field would be an ideal candidate for the description field.

**Comment by mlep** [comment]
Thanks for your feedback. I will do like you mentioned!
